/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 nutrition-box.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/nutrition-box.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.333, 0, 0.222]} rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.025}>
          <mesh geometry={nodes.Box001_1.geometry} material={materials.M_23___Default} />
          <mesh geometry={nodes.Box001_2.geometry} material={materials.left} />
        </group>
      </group>
      <group position={[0.333, 0, 0.222]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object001.geometry} material={materials.leftz} scale={0.025} />
      </group>
      <group position={[0.333, 0, 0.222]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object002.geometry} material={materials.M_24___Defaultdxss} scale={0.025} />
      </group>
      <group position={[0.333, 0, 0.222]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object003.geometry} material={materials.M_24___Default} scale={0.025} />
      </group>
      <group position={[0.333, 0, 0.222]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object004.geometry} material={materials.M_23___Default} scale={0.025} />
      </group>
    </group>
  )
}

useGLTF.preload('/nutrition-box.gltf')
